@baseUrl=http://localhost:2200/api

### Log in

# @no-cookie-jar
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "password"
}

### Log out

# @no-cookie-jar
GET {{baseUrl}}/auth/logout
Cookie: Dictionary.Session=CfDJ8B44SOkacnBHmknIh4ZbslXRmR4ftvd3Kb03elzVJliJaBYQv_r6jrQRsEbMZjlp0bqtJyWDJEInbcGIqnoyhd9BX8i_a8bf7THFJpcHp-R3A2W_neDnfuUHgNJRr3Bk1X16Kt_q5VOvQpEgQvs5vc1VobFwt3FdB5J8ZYK-2NhS4SbIU-CnFBOMAW4ziSKIRlPbQB0hudgTR9N9Q3ehlHA8qnsId_oNM7IV1IOHZ7__vbqGfSoYGOD9I7gbZ0gm3-Pp3MH5v1BenPvxxrqFHTvIL7MsohI23R5imk4XwHa7Y1qL39InKFZfi0FTuqwB3Q;
